services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:1.0.5
    environment:
      - ACCEPT_EULA=yes
      - SA_PASSWORD=S3cr3t
      - MSSQL_PID=Developer
    networks:
      - todowebapi-network
    ports:
      - 1433:1433
    volumes:
      - mssql:/var/opt/mssql
      - mssql-extensibility:/var/opt/mssql-extensibility
      - mssql-extensibility-data:/var/opt/mssql-extensibility/data
      - mssql-extensibility-log:/var/opt/mssql-extensibility/log
  postgres:
    image: postgres:13.4-alpine
    command:
      - "postgres"
      - "-c"
      - "max_locks_per_transaction=1024"
      - "-c"
      - "log_statement=all"
    environment:
      - POSTGRES_PASSWORD=S3cr3t
      - POSTGRES_USER=sa
      - PGDATA=/var/lib/postgresql/data
      - TZ=Asia/Jakarta
    networks:
      - todowebapi-network
    ports:
      - "5432:5432"
    volumes:
      - postgre-data:/var/lib/postgresql/data
  redis:
    image: redis:5.0.12-alpine
    networks:
      - todowebapi-network
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

networks:
  todowebapi-network:
    name: todowebapi_network

volumes:
  apm-data:
  mssql:
  mssql-extensibility:
  mssql-extensibility-data:
  mssql-extensibility-log:
  nsqd-data:
  postgre-data:
  redis-data:
